version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: all
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    no_unique_dist_dir: true
    binary: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

report_sizes: true

archives:
  - format: tar.gz
    files:
      - dist/*.sig
    strip_parent_binary_folder: true
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
signs:
  - artifacts: binary
    ids:
      - all
    output: true

checksum:
  algorithm: sha256
  name_template: "{{ .ProjectName }}_checksums.txt"
  ids:
    - all
  disable: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
